### PR TITLE
A lot of changes but nothing breaks

### PR DESCRIPTION
**Pull request by pickfire**
If you think that there is problem with it, you can reverse to the previous commit:

```
git checkout dfa2c92
```

or

```
git merge dfa2c92
```

### CODE REVIEW

**Comment by kingspp** [comment]
Sorry for the delay. Have you created a new branch?

**Comment by pickfire** [comment]
On 27/01/2015 13:23, Prathyush wrote:
> Sorry for the delay. Have you created a new branch?

What do you mean "Have you created a new branch"?.
I have not created any branch unless there is a major changes then I 
will create a feature branch or a develop branch.

I hope you can just look at my code and merge with it without me to 
create a pull request.
I will create a pull request when only I have a few commit.

You can look at my code and merge
---------------------------------

1. Add my repository to your remote
```
git remote add pickfire https://github.com/pickfire/RPi-AUI.git
git checkout pickfire/master    # Or you can use other branch too
git checkout master             # Return to your main branch
git merge pickfire/master       # Merge when you like and no bugs found
```

1. Take a look at my branch
```
git remote -r                   # Or -a for all local and remote branch
git checkout pickfire/master    # Or you can use other branch too
```

1. Return to your main branch
```
git checkout master
```

1. Merge my branch into your branch if you like it
```
git merge pickfire/master       # Merge when you like and no bugs found
```

**Comment by kingspp** [comment]
Okay

**Comment by kingspp** [comment]
Merged to the repo.. Indeed a lot of changes. The project is way ahead. Thanks to you. Hope you continue the development....

**Comment by pickfire** [comment]
Yes, I will continue the development. Just waiting for you to merge and test out.

**Comment by kingspp** [comment]
I have merged, I shall test it and will let you know..

**Comment by pickfire** [comment]
Everything works if you `sudo ./archi.sh` from */opt/RPi-AUI*. But the `install.sh` is useless currently as I did not change the symlink.

**Comment by kingspp** [comment]
How about a scenario where in an user is not created and sudo is not installed?

**Comment by pickfire** [comment]
What do you mean by that? By default a user is not created and `sudo` will be installed in default installation by the package `base-devel` (I had just make some changes for `defins()`). Do you mean for changing the user password or adding a user?

**Comment by kingspp** [comment]
No. By default the user is root. So sudo is not necessary for a root user

**Comment by pickfire** [comment]
But `sudo` is included in the `base-devel` package.

**Pull request merged**
