### PR TITLE
Change error in README.md - wget

### PR DESCRIPTION
**Pull request by pickfire**

### CODE REVIEW

**Comment by kingspp** [comment]
http://stackoverflow.com/questions/4037928/github-can-you-issue-pull-requests-from-the-command-line

You need to setup the git init, master and other branch stuff.
I suggest to use the Github application if available for your OS.

**Comment by ivantham** [comment]
> You need to setup the git init, master and other branch stuff.
> I suggest to use the Github application if available for your OS.
I am currently using Raspberry Pi with raspbian and archlinux.

**Comment by kingspp** [comment]
U always commit to your repo first and then ask a pull request. So it will
be there by default

On Fri, Jan 2, 2015 at 7:57 AM, Ivan Tham <notifications@github.com> wrote:

> You need to setup the git init, master and other branch stuff.
> I suggest to use the Github application if available for your OS.
> I am currently using Raspberry Pi with raspbian and archlinux.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kingspp/Raspberry-Pi-AUI/pull/15#issuecomment-68506055>
> .
>



-- 
With Regards,
Prathyush S.P
Code-Tronix <http://codetronix.in/>

**Comment by ivantham** [comment]
I have always use `git push .` and `git commit` and `git push`, but I just doesn't know how to use `request-pull`. @kingspp you are sending via email because India recently blocked access to github.com or something else? Just asking?

**Comment by ivantham** [comment]
This [article](https://help.github.com/articles/using-pull-requests/#fork--pull) is helpful.

**Comment by kingspp** [comment]
Nope, Its not yet implemented at ISP level. But even if the block , we can access using ip routing, or using holla/hotspot shield

**Comment by pickfire** [comment]
On 03/01/2015 20:07, Prathyush wrote:
> Nope, Its not yet implemented at ISP level. But even if the block , we
> can access using ip routing, or using holla/hotspot shield

Do you mean to use tor as ip routing?
     Ivan Tham

**Comment by kingspp** [comment]
Tor is just one method to do so

**Comment by pickfire** [comment]
> Tor is just one method to do so
Yeah, I use Tor in Raspberry Pi too, I am using it in Arch Linux Arm `midori`.
But too bad that `epiphany-browser` in Raspbian doesn't support socks proxy.

**Comment by pickfire** [comment]
If you use Tor, then do you use GnuPG?

**Comment by kingspp** [comment]
It is not yest blocked in India. The implementation takes a long time. I am using TOR for browsing pusposes

**Comment by pickfire** [comment]
On 12/01/2015 16:26, Prathyush wrote:
> It is not yest blocked in India. The implementation takes a long time.
> I am using TOR for browsing pusposes
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/kingspp/RPi-AUI/pull/15#issuecomment-69539789
Do you use tor on Raspberry Pi?

**Comment by kingspp** [comment]
Nope System

**Comment by pickfire** [comment]
You don't sign the releases such as v6.2 with `git tag -s`?

**Comment by kingspp** [comment]
Its jus for your reference. Your work should not go waste

**Comment by pickfire** [comment]
Should the old tag such as v0.1 alpha be deleted?

**Pull request merged**
